name: "RSS Entries Fetch Action"
description: "Traverses the entries from a RSS feed and saves it to a file"
author: "Nahue <nahuelhds@gmail.com>"
branding:
  icon: "rss"

inputs:
  feed_urls:
    description: "URL or JSON array of URLs of the RSS feed(s) to fetch"
    required: true
  destination_folder:
    description: "Relative file path where to store the found articles"
    required: true

runs:
  using: node20
  main: dist/index.js
